version: '3.9'

services:
  db:
    image: 'postgres'
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'Tech1mini'
      POSTGRES_DB: 'Tech'

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin1@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
